### ISSUE TITLE
Video tests

### ISSUE THREAD

**Issue by jamie-stackhouse** [soundcloud/areweplayingyet#52]
Are We Playing Yet encompasses many tests related to the &lt;audio&gt; element, due to the nature of the HTMLMediaElements, many tests would be duplicated between the &lt;video&gt; element.

Would SoundCloud have any interest in either extending the AWPY project to include video or a fork of the project, such as "Are We Playing Yet - Video Edition"? If you would rather not, would SoundCloud be opposed to a fork for video?

Perhaps, Are We Watching Yet?

Thank you!

**Comment by yvg** [comment]
hey @jamie-stackhouse, video is a bit out of scope for this project, but since it's open-sourced under the BSD license you are free to fork it and name it anything but AWPY.
