### ISSUE TITLE
Making standalone edition

### ISSUE THREAD

**Issue by cielavenir** [soundcloud/areweplayingyet#53]
Since areweplayingyet.org is down so often, hosting on github is great idea. But it requires static JavaScript version.

**Comment by fouasnon** [comment]
Yank it from the rendered version?

**Comment by cielavenir** [comment]
OK, let me try first.

**Comment by cielavenir** [comment]
1. I didn't know https://areweplayingyet.herokuapp.com/ is still alive.
1. Successfully hosted at https://cielavenir.github.io/areweplayingyet/ , which seems to give the same result as the original (above) site except "Follows 30x responses on src (cross domain ssl redirection)" (which seems to require server-side-js).

**Comment by cielavenir** [comment]
Anyway thank you for the help!

**Comment by fouasnon** [comment]
Sounds like you figured it out all by yourself :)

**Comment by Anutrix** [comment]
areweplayingyet.com and areweplayingyet.org now just redirects to https://soundcloud.com .
